### ISSUE TITLE
Unidentified code point

### ISSUE THREAD

**Issue by MoonfirePDX** [thewakingsands/ffxiv-axis-font-icons#1]
Code point e03e is for random number generation or dice rolling in game chat with the commands /dice and /random

**Comment by oott123** [comment]
![image](https://user-images.githubusercontent.com/905663/202886150-50893c6c-b8f9-463d-92a4-d9a32b25c472.png)

/dice or /random uses colorful fonticon, not axis font icons.

Please provide screenshots in game if I'm missing something.

Thanks!

**Comment by MoonfirePDX** [comment]
You are correct, I had misremembered! Closing as user error 😄
